"""
Generate demo data for the Scalable Semantic Shift Detection pipeline.

Creates two time-period corpora (JSON lines format) and a gold standard file.
Target words are chosen to demonstrate both high and low semantic shift:
  - High shift: cell, mouse, apple, cloud, virus, net
  - Low shift: water, house, book, tree, garden, river
"""

import json
import os
import random

random.seed(42)

# ---- Sentence templates for each word in each period ----

# Period 1 (1960): traditional/original meanings
period1_sentences = {
    "cell": [
        "The scientist examined the cell under the microscope to study its structure.",
        "Every living organism is composed of at least one cell.",
        "The cell membrane protects the interior of the cell from the outside environment.",
        "The prisoner was locked in a small cell with barely any light.",
        "The research team discovered a new type of blood cell.",
        "Each cell contains genetic material that determines its function.",
        "The biology teacher explained how a cell divides during mitosis.",
        "The monks lived in a small cell within the monastery walls.",
        "A single cell can give rise to an entire organism through division.",
        "The nerve cell transmits signals throughout the body.",
        "Scientists observed the cell under a powerful electron microscope.",
        "The plant cell has a rigid wall that provides structural support.",
        "White blood cell counts are important for diagnosing infections.",
        "The cell is the basic unit of life in all organisms.",
        "Under the microscope the cell appeared to be dividing rapidly.",
        "The bacterial cell reproduces by splitting into two identical cells.",
        "Red blood cell production occurs primarily in the bone marrow.",
        "The biology professor demonstrated cell staining techniques in class.",
        "Each cell in the human body contains the complete genetic code.",
        "The cell theory states that all living things are made of cells.",
        "Stem cell research has opened new possibilities in medicine.",
        "The animal cell lacks the rigid wall found in plant cells.",
        "Researchers cultured the cell in a laboratory dish for study.",
        "The prison cell was cold and damp throughout the winter months.",
        "Cancer occurs when cell division goes out of control.",
        "A typical human cell is about ten micrometers in diameter.",
        "The egg cell is the largest cell in the human body.",
        "Cell biology is a fundamental branch of the life sciences.",
        "The muscle cell contracts to produce movement in the body.",
        "Scientists discovered how the cell repairs damaged genetic material.",
    ],
    "mouse": [
        "The cat chased the mouse across the kitchen floor.",
        "A small mouse was hiding behind the cupboard in the corner.",
        "The mouse nibbled on the piece of cheese left on the table.",
        "Farmers use traps to catch the mouse that eats their grain.",
        "The children watched the little mouse scurry through the garden.",
        "A field mouse built its nest in the tall grass near the barn.",
        "The mouse is a common rodent found throughout the world.",
        "The laboratory mouse is used extensively in medical research.",
        "A tiny mouse appeared from a hole in the wall last night.",
        "The owl swooped down to catch the mouse in the meadow.",
        "Mice and rats are closely related rodent species.",
        "The pet mouse ran happily on its exercise wheel all evening.",
        "The house mouse is one of the most common pests in homes.",
        "A mouse can squeeze through surprisingly small openings.",
        "The brown mouse found shelter from the rain under a bush.",
        "Scientists bred the laboratory mouse for specific genetic traits.",
        "The mouse ran along the edge of the wall to avoid detection.",
        "Children love reading stories about the clever little mouse.",
        "A mouse family had taken up residence in the old shed.",
        "The white mouse was kept as a pet by the young boy.",
        "Researchers studied the mouse to understand mammalian genetics better.",
        "The mouse escaped from the trap and disappeared into the wall.",
        "Field mouse populations increase dramatically during warm summers.",
        "The cat sat patiently waiting for the mouse to appear again.",
        "A deer mouse can carry diseases that affect human health.",
        "The mouse squeaked loudly when it was cornered by the dog.",
        "Laboratory mouse experiments contributed to many medical breakthroughs.",
        "The tiny mouse left footprints in the dust on the shelf.",
        "A mouse can survive on very small amounts of food each day.",
        "The barn mouse stored seeds in a hidden nest for winter.",
    ],
    "apple": [
        "She picked a ripe apple from the tree in the orchard.",
        "The apple pie that grandmother made was delicious and sweet.",
        "An apple a day keeps the doctor away said the old proverb.",
        "The farmer harvested bushels of apple from his orchard this fall.",
        "Children enjoyed eating a fresh apple during their lunch break.",
        "The apple tree in the garden produced fruit every autumn.",
        "He peeled the apple carefully before slicing it for the salad.",
        "The red apple glistened with dew in the morning sunlight.",
        "Apple cider is a popular drink during the harvest festival.",
        "She baked an apple cake for the school fundraiser event.",
        "The green apple was sour but refreshing on a hot day.",
        "Workers at the apple orchard start their harvest in September.",
        "The apple fell from the tree and rolled down the hill.",
        "Fresh apple juice is a healthy alternative to sugary drinks.",
        "The apple blossom signaled the arrival of spring in the valley.",
        "He packed an apple in his lunch box every single morning.",
        "The apple harvest was particularly abundant this year.",
        "She made apple sauce from the fruit she gathered yesterday.",
        "The golden apple was the prize at the county fair competition.",
        "Apple trees require careful pruning to produce good fruit annually.",
        "The worm had eaten through the core of the apple completely.",
        "Caramel apple treats are a favorite at autumn carnivals everywhere.",
        "The apple variety known as Granny Smith is particularly tart.",
        "She sliced the apple into thin wedges for the children to eat.",
        "The orchard had over five hundred apple trees planted in rows.",
        "Apple vinegar has been used as a folk remedy for centuries.",
        "The apple crumble served with cream was the best dessert offered.",
        "Wild apple trees grow along the roads in this rural area.",
        "He compared the different apple varieties at the farmers market stall.",
        "The basket was overflowing with freshly picked apple from the farm.",
    ],
    "cloud": [
        "A dark cloud gathered over the mountain before the storm arrived.",
        "The white cloud drifted slowly across the bright blue sky today.",
        "Rain began to fall as the cloud grew darker and thicker.",
        "The pilot flew the airplane above the cloud layer for safety.",
        "A cloud of dust rose from the dirt road behind the car.",
        "The sunset painted the cloud in brilliant shades of orange and pink.",
        "Heavy cloud cover blocked the sunlight throughout the afternoon hours.",
        "The mountain peak was hidden behind a thick cloud of fog.",
        "Children lay on the grass watching cloud shapes drift by overhead.",
        "A thunder cloud formed rapidly in the warm afternoon sky.",
        "The cloud parted briefly to reveal the bright moon above.",
        "Meteorologists tracked the cloud formation as it moved across the region.",
        "A wispy cloud stretched across the horizon like a thin veil.",
        "The rain cloud moved eastward bringing showers to the coastal areas.",
        "Farmers watched the cloud anxiously hoping for much needed rainfall.",
        "The fluffy white cloud resembled a sheep floating in the sky.",
        "Storm cloud often produce lightning and heavy rainfall in summer.",
        "A cloud of smoke rose from the chimney of the old house.",
        "The airplane disappeared into the cloud and was no longer visible.",
        "Cloud formations can tell experienced sailors about coming weather patterns.",
        "The morning cloud burned away as the sun rose higher overhead.",
        "A massive cloud bank approached from the west bringing cold weather.",
        "The cloud cast a shadow over the valley below the mountain.",
        "Cirrus cloud at high altitude indicate fair weather approaching soon.",
        "The dark cloud threatened rain but ultimately passed without dropping any.",
        "A beautiful rainbow appeared after the rain cloud finally moved away.",
        "The pilot navigated carefully through the turbulent cloud during the flight.",
        "Cloud patterns change dramatically with the seasons in this climate region.",
        "The fog was essentially a cloud that formed close to the ground.",
        "Watching cloud drift by is a relaxing pastime on lazy afternoons.",
    ],
    "virus": [
        "The doctor diagnosed the patient with a virus that causes fever.",
        "A new virus was discovered in the tropical rainforest last year.",
        "The influenza virus spreads rapidly during the cold winter months.",
        "Scientists studied the virus under an electron microscope for details.",
        "The virus caused an epidemic that affected thousands of people.",
        "Vaccination is the most effective way to prevent virus infection.",
        "The virus mutated and became more resistant to existing treatments.",
        "Doctors warned that the virus could spread through contaminated water.",
        "The research team isolated the virus in their laboratory facility.",
        "A virus is a microscopic infectious agent that replicates inside cells.",
        "The common cold virus is one of the most frequent infections.",
        "Public health officials worked to contain the spread of the virus.",
        "The virus was transmitted through direct contact between infected individuals.",
        "Scientists developed a new vaccine to combat the dangerous virus.",
        "The hospital treated hundreds of patients infected with the virus.",
        "A virus can only reproduce by invading a living host cell.",
        "The virus outbreak prompted authorities to declare a state of emergency.",
        "Researchers identified the virus as a new strain of influenza type.",
        "The virus was particularly dangerous for elderly and immunocompromised patients.",
        "Hand washing is an effective measure to prevent virus transmission.",
        "The virus attacked the respiratory system causing severe breathing problems.",
        "Medical researchers worked around the clock to understand the new virus.",
        "The virus spread from animals to humans in the rural community.",
        "A global effort was launched to develop a cure for the virus.",
        "The virus weakened over time and eventually the epidemic subsided.",
        "Blood tests confirmed that the patient had been infected with the virus.",
        "The virus was resistant to all known antibiotics available at the time.",
        "Scientists mapped the genetic structure of the virus for further study.",
        "The virus caused inflammation in the lungs leading to pneumonia cases.",
        "Prevention strategies against the virus included quarantine and isolation measures.",
    ],
    "net": [
        "The fisherman cast his net into the sea to catch fish.",
        "A butterfly net is useful for collecting insect specimens in the field.",
        "The tennis player hit the ball directly into the net accidentally.",
        "They repaired the fishing net that had been torn by the rocks.",
        "The net was spread across the river to catch migrating salmon.",
        "A safety net was installed beneath the construction workers high above.",
        "The soccer ball sailed past the goalkeeper and into the net.",
        "Fishermen mended their net on the dock after returning from the sea.",
        "The basketball went cleanly through the net without touching the rim.",
        "A mosquito net protected the travelers from insect bites at night.",
        "The net caught dozens of fish during the early morning trawl.",
        "Volleyball players jumped high to spike the ball over the net.",
        "The spider spun a delicate net to catch flying insects nearby.",
        "Farmers used a net to protect their crops from hungry birds.",
        "The fishing net was heavy with the weight of the fresh catch.",
        "A hair net kept the workers hair tidy during food preparation.",
        "The net profit of the company increased significantly this quarter.",
        "Children played badminton hitting the shuttlecock back and forth over the net.",
        "The net was carefully designed to catch only fish of a certain size.",
        "A cargo net secured the heavy equipment during transport by ship.",
        "The trawler dragged its enormous net across the ocean floor today.",
        "The goalkeeper dove to his left but the ball hit the net.",
        "A net of ropes was used to climb the steep cliff face.",
        "The butterfly collector carried a fine mesh net through the meadow.",
        "Fish were tangled in the net and had to be freed carefully.",
        "The trapeze artist performed without a safety net below her platform.",
        "A net was stretched across the opening to keep animals from entering.",
        "The shrimp net was pulled through shallow waters near the shoreline.",
        "Players celebrated as the ball hit the back of the net decisively.",
        "The old fishing net hung drying in the sun on the pier.",
    ],
    "water": [
        "She drank a glass of cold water after her morning exercise.",
        "The water in the lake was crystal clear and refreshingly cool.",
        "Farmers irrigated their fields with water from the nearby river.",
        "Clean drinking water is essential for human health and survival.",
        "The water flowed gently downstream towards the ocean far away.",
        "Children splashed happily in the water at the swimming pool.",
        "The water supply to the town was disrupted by the storm.",
        "Plants need water and sunlight to grow healthy and strong.",
        "The water level in the reservoir dropped dramatically during the drought.",
        "She boiled water on the stove to make tea for her guests.",
        "The water was warm enough for swimming by late afternoon.",
        "Fresh water sources are becoming increasingly scarce around the world.",
        "The boat sailed smoothly across the calm water of the bay.",
        "Water pollution is a serious environmental problem in many countries.",
        "He carried two buckets of water from the well to the house.",
        "The water tower provides pressure to the entire community supply system.",
        "Rain water collected in barrels can be used to water gardens.",
        "The water temperature dropped as the winter months approached gradually.",
        "Water conservation is important for sustaining our natural resources long term.",
        "The glass of water sat untouched on the table all morning.",
        "Water covers approximately seventy percent of the surface of the earth.",
        "The water treatment plant ensures the safety of the public supply.",
        "Mountain streams carry fresh water down to the valleys below naturally.",
        "She filled the watering can with water for her garden flowers.",
        "The water was tested regularly for quality and contamination levels.",
        "A water main broke flooding the street with gallons of water.",
        "The healing properties of mineral water have been known for centuries.",
        "Water pressure in the pipes decreased during peak usage hours.",
        "The water cycle involves evaporation condensation and precipitation processes.",
        "They installed a new water filtration system in their home recently.",
    ],
    "house": [
        "The family moved into their new house on the quiet street.",
        "She painted the house white with blue shutters on every window.",
        "The old house had a beautiful garden with roses and tulips.",
        "He built a house from wood and stone on the hillside.",
        "The house was warm and cozy during the cold winter nights.",
        "They inherited the house from their grandparents who had lived there.",
        "The house needed extensive repairs after the severe winter storm.",
        "A small house stood alone at the end of the dirt road.",
        "The house had three bedrooms a kitchen and a large living room.",
        "She decorated the house with flowers for the holiday celebration.",
        "The brick house withstood the strong winds better than its neighbors.",
        "Children played in the yard behind the house every afternoon.",
        "The house was built in the traditional style of the region.",
        "A fire damaged the roof of the house but everyone escaped safely.",
        "The house was surrounded by tall oak trees providing shade.",
        "They sold the house and moved to a smaller apartment downtown.",
        "The house was quiet and peaceful on the lazy Sunday morning.",
        "A new house was being constructed on the empty lot next door.",
        "The house had been in the family for three generations already.",
        "She cleaned the house thoroughly before the guests arrived for dinner.",
        "The house overlooked the valley with a spectacular view of the mountains.",
        "He repaired the leaking roof of the old house before winter came.",
        "The house was furnished with antique furniture from the previous century.",
        "A garden path led from the gate to the front door of the house.",
        "The house was located in a quiet neighborhood near good schools.",
        "They renovated the house completely changing its interior layout design.",
        "The house had a large fireplace that heated the entire ground floor.",
        "Birds nested under the eaves of the house every spring season.",
        "The house price in this area has increased substantially over the years.",
        "A white picket fence surrounded the charming little house on the corner.",
    ],
    "book": [
        "She read a book about the history of ancient civilizations.",
        "The book was published by a well known academic press last year.",
        "He borrowed a book from the library and returned it on time.",
        "The author signed copies of her new book at the bookstore event.",
        "A good book can transport you to another world entirely.",
        "The children gathered around to hear the teacher read from the book.",
        "She placed the book on the shelf alongside the other volumes.",
        "The book contained valuable information about medicinal plants and herbs.",
        "He wrote a book about his travels through South America.",
        "The book had beautiful illustrations on every other page throughout.",
        "She found an old book in the attic covered with dust.",
        "The book was translated into over twenty different languages worldwide.",
        "He spent the afternoon reading a book in the garden shade.",
        "The book fair attracted thousands of visitors from across the country.",
        "A book of poems was the most treasured gift she received.",
        "The professor recommended a book that explained the theory clearly.",
        "She always carried a book in her bag wherever she went.",
        "The book review in the newspaper was very positive and encouraging.",
        "He finished reading the book and immediately started another one.",
        "The cookbook had recipes from various cultures around the world.",
        "A book about birds helped him identify species in his garden.",
        "The library had every book the researcher needed for her study.",
        "She donated a box of book to the local school library.",
        "The book was bound in leather with gold lettering on the spine.",
        "He discovered a rare book at the antique store downtown.",
        "The book provided a comprehensive overview of modern physics concepts.",
        "Children love picture book with colorful drawings and simple stories.",
        "The book was so popular it went through ten printings.",
        "She wrote her thoughts in a book before going to sleep.",
        "The history book described events that shaped the modern world.",
    ],
    "tree": [
        "The old oak tree stood tall in the center of the park.",
        "Birds built their nests in the branches of the tree.",
        "The tree provided welcome shade during the hot summer afternoon.",
        "They planted a tree in the garden to commemorate the occasion.",
        "The tree lost all its leaves as autumn turned to winter.",
        "A fallen tree blocked the road after the severe thunderstorm.",
        "The pine tree remained green throughout the cold winter months.",
        "Children loved to climb the large tree in the backyard.",
        "The tree had been growing in the same spot for over a century.",
        "She sat under the tree reading a book on a sunny day.",
        "The fruit tree produced an abundance of peaches this year.",
        "A tree surgeon was called to remove the diseased branches safely.",
        "The Christmas tree was decorated with lights and colorful ornaments.",
        "The tree roots spread wide beneath the surface of the ground.",
        "An ancient tree in the forest was believed to be sacred.",
        "The tree swayed gently in the breeze on a calm evening.",
        "He carved his initials into the bark of the tree long ago.",
        "The tree blossomed in spring covering itself with pink flowers.",
        "A tree lined avenue led to the entrance of the estate.",
        "The maple tree turned brilliant red and orange in the fall.",
        "The tree was struck by lightning during the thunderstorm last night.",
        "A family of squirrels lived in the hollow of the old tree.",
        "The tree cast long shadows across the lawn in the late afternoon.",
        "She identified the tree species using a field guide she carried.",
        "The tree canopy filtered the sunlight creating dappled patterns below.",
        "A young tree was planted to replace the one that had fallen.",
        "The willow tree hung its branches gracefully over the pond edge.",
        "Birds sang from the top of the tree early every morning.",
        "The tree grew taller each year reaching towards the sky above.",
        "An apple tree in the garden attracted bees during the blossom season.",
    ],
    "garden": [
        "She spent every morning tending to her beautiful flower garden.",
        "The garden was full of colorful roses tulips and daffodils.",
        "He grew vegetables in the garden behind the house every year.",
        "The garden path was lined with lavender plants on both sides.",
        "A stone fountain stood at the center of the formal garden.",
        "The community garden provided fresh produce for the neighborhood families.",
        "She designed the garden with both beauty and practicality in mind.",
        "The garden was enclosed by a tall hedge for privacy.",
        "Butterflies visited the garden attracted by the fragrant flowers blooming.",
        "The botanical garden housed plants from every continent on earth.",
        "He installed a pond in the garden where goldfish now swim.",
        "The herb garden provided fresh seasoning for the kitchen meals daily.",
        "The garden looked beautiful after the spring rain brought new growth.",
        "A vegetable garden can save money on groceries throughout the summer.",
        "The children played hide and seek among the bushes in the garden.",
        "She read books about garden design to plan her new layout.",
        "The garden was inherited from the previous owners of the property.",
        "Morning dew sparkled on the flowers in the garden at dawn.",
        "The garden club met monthly to share tips and plant cuttings.",
        "A bench in the garden was the perfect spot for quiet reflection.",
        "The Japanese garden featured a small bridge over a koi pond.",
        "The garden produced enough tomatoes to make sauce for the whole year.",
        "She planted seeds in the garden hoping they would bloom by summer.",
        "The garden wall was covered with climbing ivy and wisteria vines.",
        "A scarecrow stood in the garden to keep birds away from crops.",
        "The roof garden provided a green space in the busy city center.",
        "The garden soil was rich and fertile from years of composting.",
        "He spent weekends working in the garden pruning and weeding carefully.",
        "The cottage garden had a wild natural charm that visitors loved.",
        "The garden gate creaked as she opened it to water the plants.",
    ],
    "river": [
        "The river flowed gently through the valley toward the distant sea.",
        "Children swam in the river during the hot summer afternoons.",
        "The river provided water for the crops in the surrounding farmland.",
        "A bridge spanned the wide river connecting the two towns together.",
        "The river was swollen with rain and flowed faster than usual.",
        "Fishermen cast their lines into the river hoping for a good catch.",
        "The river wound through the forest creating a peaceful natural scene.",
        "A small boat drifted lazily down the river in the afternoon sun.",
        "The river banks were covered with wildflowers during the spring season.",
        "The town was built alongside the river for access to fresh water.",
        "The river delta formed a rich ecosystem for many species of wildlife.",
        "She walked along the river path enjoying the cool morning breeze.",
        "The river was too deep to cross without a bridge or boat.",
        "Flooding occurred when the river overflowed its banks after heavy rain.",
        "The river was an important trade route in earlier centuries of history.",
        "Kayakers paddled down the river through the scenic mountain gorge.",
        "The river water was tested for pollutants by environmental scientists.",
        "A river otter was spotted playing among the rocks near the shore.",
        "The river provided power for the old mill that ground grain.",
        "Trees lined both sides of the river creating a shady canopy.",
        "The river froze solid during the extremely cold winter that year.",
        "A dam was built across the river to generate hydroelectric power.",
        "The river mouth opened into a wide bay where ships anchored.",
        "The river supported a thriving fishing industry in the coastal region.",
        "He sketched the river scene from the hilltop overlooking the valley.",
        "The river carried fallen leaves downstream during the autumn months.",
        "Pollution threatened the river ecosystem and the wildlife that depended on it.",
        "The river level dropped during the drought exposing the rocky riverbed.",
        "A ferry carried passengers across the river several times each day.",
        "The river was the lifeblood of the community providing water and food.",
    ],
}

# Period 2 (1990): for shift words, meanings change; for stable words, similar contexts
period2_sentences = {
    "cell": [
        "She answered her cell phone while waiting for the bus to arrive.",
        "The new cell phone model has an improved camera and longer battery.",
        "He forgot his cell phone at home and felt completely disconnected.",
        "Cell phone towers were installed across the rural area for coverage.",
        "The cell phone rang loudly during the quiet meeting with clients.",
        "Everyone in the office carries a cell phone for communication purposes.",
        "She upgraded her cell phone to the latest model available this month.",
        "The cell phone plan includes unlimited calling and text messaging features.",
        "He used his cell phone to navigate through the unfamiliar city streets.",
        "Cell phone reception was poor in the mountainous region near the border.",
        "The cell phone has become an essential device in modern daily life.",
        "She texted her friend using the cell phone during her lunch break.",
        "Cell phone technology has advanced dramatically over the past decade.",
        "He dropped his cell phone and cracked the screen badly unfortunately.",
        "The cell phone bill was higher than expected because of roaming charges.",
        "Students were asked to turn off their cell phone during the exam.",
        "The cell phone charger was left behind at the hotel room accidentally.",
        "Cell phone signals can be disrupted during severe weather conditions.",
        "She used her cell phone camera to capture the beautiful sunset view.",
        "The cell phone vibrated in his pocket alerting him to a new message.",
        "Cell phone usage while driving is prohibited by law in many places.",
        "He compared different cell phone brands before making his purchase decision.",
        "The cell phone network was overloaded during the major concert event.",
        "She bought a protective case for her new cell phone immediately.",
        "Cell phone apps have transformed how people manage their daily tasks.",
        "The cell phone industry generates billions of dollars in revenue annually.",
        "He set an alarm on his cell phone to wake up early tomorrow.",
        "Cell phone cameras have largely replaced traditional point and shoot cameras.",
        "The broken cell phone needed to be repaired at a service center.",
        "Cell phone data plans have become more affordable over recent years.",
    ],
    "mouse": [
        "She clicked the mouse to open the document on her computer screen.",
        "The wireless mouse made it easier to work from the couch comfortably.",
        "He bought a new mouse for his computer because the old one broke.",
        "The optical mouse is more accurate than older mechanical mouse designs.",
        "She moved the mouse across the pad to position the cursor precisely.",
        "The computer mouse was invented to make interaction with computers easier.",
        "He connected the mouse to the laptop using a small USB receiver.",
        "The gaming mouse has extra buttons for quick actions during play.",
        "The mouse pointer froze on the screen and she had to restart.",
        "A mouse pad improves the tracking performance of optical mouse devices.",
        "He adjusted the mouse sensitivity settings for better control on screen.",
        "The bluetooth mouse paired automatically with the new tablet device.",
        "She scrolled down the page using the mouse wheel to read more.",
        "The mouse cursor moved erratically because the sensor was dirty.",
        "A new ergonomic mouse was designed to reduce wrist strain at work.",
        "He dragged the file icon using the mouse to the recycle bin.",
        "The mouse button was stuck and needed to be replaced soon.",
        "She selected the text by clicking and dragging with the mouse carefully.",
        "The mouse cable was tangled with other wires on the desk.",
        "Computer mouse technology has evolved significantly since its invention decades ago.",
        "He right clicked the mouse to access the context menu options.",
        "The laser mouse provides smoother tracking on various surface types.",
        "She used the mouse to navigate through the complex software interface.",
        "The mouse settings can be customized in the system preferences panel.",
        "A trackball mouse is preferred by some users for precision tasks.",
        "He replaced the batteries in his wireless mouse when it stopped working.",
        "The mouse is one of the most essential computer input devices today.",
        "She double clicked the mouse to launch the application on her desktop.",
        "The mouse design has become more ergonomic to prevent repetitive strain.",
        "Gamers prefer a high precision mouse for competitive play tournaments.",
    ],
    "apple": [
        "Apple released its latest smartphone with revolutionary display technology today.",
        "She bought an Apple laptop for her college studies this semester.",
        "The Apple store was crowded with customers waiting for the new product.",
        "Apple stock prices rose sharply after the quarterly earnings announcement.",
        "He downloaded the app from the Apple app store on his phone.",
        "Apple introduced a new operating system with enhanced security features.",
        "The Apple ecosystem integrates seamlessly across all its devices and services.",
        "She switched from a PC to an Apple computer for better design work.",
        "Apple announced a new partnership with a major streaming service provider.",
        "The Apple watch tracks health metrics including heart rate and activity.",
        "He used his Apple tablet to take notes during the lecture.",
        "Apple invested heavily in artificial intelligence and machine learning research.",
        "The Apple conference showcased several innovative products and software updates.",
        "She set up her new Apple phone with all her previous data.",
        "Apple music streaming service now has millions of subscribers worldwide.",
        "The Apple design philosophy emphasizes simplicity and user experience.",
        "He repaired his Apple laptop at the authorized service center downtown.",
        "Apple revenues exceeded expectations driven by strong iPhone sales globally.",
        "The Apple brand is recognized as one of the most valuable worldwide.",
        "She used Apple pay to complete the purchase quickly at the store.",
        "Apple developed a new chip that significantly improves processing speed.",
        "The Apple software update fixed several bugs and improved performance greatly.",
        "He attended the Apple developer conference to learn about new tools.",
        "Apple shares traded higher following the positive product launch event.",
        "The Apple TV streaming device competes with other major platforms available.",
        "She synced her data across all her Apple devices effortlessly.",
        "Apple is committed to using renewable energy in all its operations.",
        "The new Apple headphones feature advanced noise cancellation technology built in.",
        "He prefers Apple products because of their reliability and build quality.",
        "Apple continues to innovate in the consumer electronics market every year.",
    ],
    "cloud": [
        "The company migrated all its data to the cloud for better access.",
        "Cloud computing has transformed how businesses store and process information.",
        "She saved her photos to the cloud so they would not be lost.",
        "Cloud services allow users to access their files from any device.",
        "The cloud platform provides scalable computing resources on demand for clients.",
        "He set up automatic cloud backup for all his important documents.",
        "Cloud storage is more cost effective than maintaining physical servers onsite.",
        "The cloud infrastructure handled millions of requests during the peak period.",
        "She accessed the cloud application from her phone while traveling abroad.",
        "Cloud security is a major concern for businesses storing sensitive data.",
        "The cloud provider guaranteed uptime of more than ninety nine percent.",
        "He learned cloud architecture to advance his career in technology.",
        "Cloud based software eliminates the need for local installation completely.",
        "The enterprise cloud solution reduced operating costs by thirty percent overall.",
        "She uploaded the presentation to the cloud for her team to review.",
        "Cloud technology enables remote work by providing access to shared resources.",
        "The cloud database was optimized for faster query performance across regions.",
        "He managed the cloud deployment using automated tools and scripts.",
        "Cloud computing relies on large data centers distributed around the world.",
        "The cloud service experienced a brief outage but recovered quickly that day.",
        "She migrated the legacy system to a modern cloud platform successfully.",
        "Cloud solutions offer flexibility that traditional computing cannot match easily.",
        "The cloud market is expected to grow significantly in the coming years.",
        "He configured the cloud firewall to protect against unauthorized access attempts.",
        "Cloud native applications are designed specifically to run in cloud environments.",
        "The company chose a multi cloud strategy for redundancy and performance.",
        "She monitored cloud resource usage to optimize costs for the organization.",
        "Cloud adoption has accelerated dramatically across all industries globally.",
        "The cloud API allowed developers to integrate services seamlessly into apps.",
        "He completed a certification in cloud computing to improve his job prospects.",
    ],
    "virus": [
        "The computer virus infected thousands of machines through email attachments.",
        "She installed antivirus software to protect her computer from virus attacks.",
        "The virus corrupted all the files on the hard drive irreversibly.",
        "A new computer virus was spreading rapidly across the internet worldwide.",
        "He ran a virus scan on his computer after noticing strange behavior.",
        "The virus was designed to steal personal information from infected computers.",
        "Computer virus protection requires regular software updates and user vigilance.",
        "The virus replicated itself and spread to every computer on the network.",
        "She lost all her work when the virus destroyed her system files.",
        "The virus was distributed through a malicious website that users visited.",
        "Antivirus programs detect and remove virus threats from computer systems.",
        "He accidentally downloaded a virus disguised as a legitimate software update.",
        "The virus slowed down the computer significantly until it was removed.",
        "A virus warning appeared on the screen alerting the user immediately.",
        "The virus exploited a security vulnerability in the operating system code.",
        "She had to reformat her computer after the virus attack destroyed everything.",
        "The company network was shut down to prevent the virus from spreading.",
        "Computer virus creators face serious legal consequences for their harmful actions.",
        "The virus encrypted files and demanded a ransom for their release.",
        "He educated employees about how to avoid clicking on virus laden links.",
        "The virus affected computers running outdated versions of the operating system.",
        "A particularly destructive virus caused millions of dollars in damage globally.",
        "The virus signature was added to the antivirus database for detection.",
        "She backed up her files regularly in case a virus attacked again.",
        "The virus was traced back to a server located in eastern Europe.",
        "Computer virus attacks have become more sophisticated and harder to detect.",
        "The virus disabled the firewall before spreading to other connected devices.",
        "He recovered most of his data after the virus was successfully removed.",
        "A virus can lie dormant in a system before activating at a set time.",
        "The security team patched the vulnerability that the virus had exploited.",
    ],
    "net": [
        "She searched the net for information about the upcoming conference event.",
        "The net has revolutionized how people communicate and access information daily.",
        "He found the answer to his question by searching the net quickly.",
        "Shopping on the net has become increasingly popular in recent years.",
        "The net provides access to vast amounts of knowledge and resources.",
        "She met her business partner through a networking site on the net.",
        "News spreads faster on the net than through traditional media channels.",
        "He downloaded the software from a trusted site on the net safely.",
        "The net has transformed education by making learning resources widely available.",
        "She read reviews on the net before deciding which product to purchase.",
        "The net connects billions of people across the globe instantaneously.",
        "He published his research paper on the net for open access reading.",
        "Social media on the net has changed how people interact with others.",
        "The net offers opportunities for remote work that were impossible before.",
        "She took an online course on the net to learn new skills.",
        "The net has become an essential tool for modern business operations.",
        "He streamed music and videos through services available on the net.",
        "The net allows instant communication through email and messaging platforms.",
        "Privacy concerns on the net have become a major topic of debate.",
        "She advertised her products on the net reaching a global audience.",
        "The net has made it possible to work from anywhere in the world.",
        "He used the net to video call his family living overseas regularly.",
        "The net economy has created millions of new jobs across industries.",
        "She managed her finances using banking services available on the net.",
        "The net has democratized access to information that was once exclusive.",
        "He troubleshooted his computer problem by searching for solutions on the net.",
        "E-commerce on the net has disrupted traditional retail business models.",
        "She learned programming through free tutorials available on the net easily.",
        "The net has enabled global collaboration on scientific research projects.",
        "He submitted his job application through the company portal on the net.",
    ],
    "water": [
        "She drank a bottle of water after finishing her workout at the gym.",
        "The water in the swimming pool was heated to a comfortable temperature.",
        "Clean water access remains a critical issue in many developing countries.",
        "The water filtration system removed impurities before distribution to homes.",
        "He filled the water tank before the predicted drought period began.",
        "Water conservation programs helped reduce consumption in the drought affected area.",
        "The water quality report showed all parameters were within safe limits.",
        "She ordered a glass of water with her meal at the restaurant.",
        "The water main burst causing flooding in the downtown area overnight.",
        "Water recycling technology has improved significantly in recent years.",
        "He tested the water before allowing children to swim in the lake.",
        "The water company announced rate increases effective from next month.",
        "Water damage to the basement was covered by the insurance policy.",
        "She used mineral water for cooking because the tap water tasted odd.",
        "The water heater needed replacement after fifteen years of reliable service.",
        "Water sports including kayaking and surfing are popular at the beach.",
        "He installed a water purifier in the kitchen for drinking water.",
        "The water supply was temporarily shut off for maintenance work today.",
        "Water usage statistics showed a decrease compared to the previous year.",
        "She carried a water bottle everywhere to stay hydrated throughout the day.",
        "The water feature in the park attracted visitors during the summer months.",
        "Water testing revealed elevated levels of minerals but nothing harmful found.",
        "He watered the garden every evening using recycled water from the tank.",
        "The water pressure improved after the pipes were replaced last week.",
        "Water scarcity is one of the major challenges facing the world today.",
        "She learned about the water cycle in her environmental science class.",
        "The water bill was lower this month thanks to conservation efforts.",
        "Water safety guidelines were posted at the public swimming pool entrance.",
        "He studied water resource management as part of his engineering degree.",
        "The bottled water industry has grown substantially in the past decade.",
    ],
    "house": [
        "The house was recently renovated with modern appliances and fixtures.",
        "She bought a house in the suburbs with a large backyard area.",
        "The house prices in the city have increased dramatically this year.",
        "He listed the house for sale and received multiple offers quickly.",
        "The house was equipped with smart home technology throughout every room.",
        "She decorated the house in a minimalist style with neutral colors.",
        "The house had energy efficient windows that reduced heating costs significantly.",
        "He took out a mortgage to finance the purchase of the house.",
        "The house inspection revealed minor issues that were easily repaired.",
        "She hosted a dinner party at her house for close friends.",
        "The house was located in a safe neighborhood with good schools nearby.",
        "He painted the house exterior in a warm beige color last week.",
        "The house had a spacious kitchen with granite countertops and new cabinets.",
        "She moved into the house and immediately began making it feel like home.",
        "The house was built using sustainable materials and green building practices.",
        "He invested in the house as a rental property for extra income.",
        "The house fire was caused by a faulty electrical connection in the wall.",
        "She planted trees around the house for shade and privacy screening.",
        "The house was appraised at a value higher than the purchase price.",
        "He added a deck to the house for outdoor entertaining during summer.",
        "The house had central air conditioning which made summers very comfortable.",
        "She chose the house because of its proximity to public transportation.",
        "The house was well maintained with regular upkeep by the previous owners.",
        "He rented out the house during the vacation season for additional revenue.",
        "The house had a two car garage with extra storage space available.",
        "She organized the house to maximize space in every room efficiently.",
        "The house was featured in a home design magazine last month.",
        "He installed solar panels on the house roof to reduce energy bills.",
        "The house had a large garden that was perfect for growing vegetables.",
        "She fell in love with the house the moment she walked through the door.",
    ],
    "book": [
        "She downloaded the book onto her electronic reader for the flight.",
        "The book was available in both paperback and digital formats now.",
        "He ordered the book online and received it within two business days.",
        "The author promoted her new book through social media and interviews.",
        "The book became a bestseller within the first week of its release.",
        "She left a review for the book on the online bookstore site.",
        "The book club met monthly to discuss their latest selection together.",
        "He listened to the audio version of the book during his commute.",
        "The book was adapted into a successful television series last year.",
        "She used the book as a reference for her research project work.",
        "The book fair featured signing events with popular authors all weekend.",
        "He published the book independently using a self publishing platform online.",
        "The book explores themes of identity and belonging in modern society.",
        "She gifted the book to her friend for their birthday celebration.",
        "The book was written by an expert in the field of psychology.",
        "He highlighted important passages in the book for later review.",
        "The book series has sold millions of copies across the globe.",
        "She found the book insightful and recommended it to all her colleagues.",
        "The book discusses the impact of technology on human relationships.",
        "He returned the overdue book to the library and paid the fine.",
        "The book was translated into multiple languages reaching a wider audience.",
        "She wrote a book report summarizing the main arguments and conclusions.",
        "The book signing event at the store attracted hundreds of eager fans.",
        "He collected first editions of his favorite book as a hobby.",
        "The book provides practical advice for managing personal finances effectively.",
        "She read the book in one sitting because it was so engaging.",
        "The book won several literary awards for its exceptional storytelling quality.",
        "He donated the book to a charity that promotes literacy worldwide.",
        "The book was praised by critics for its original perspective on history.",
        "She plans to write a book about her experiences traveling the world.",
    ],
    "tree": [
        "The city planted a tree along every new street for shade.",
        "The tree in the front yard needed trimming before the storm season.",
        "She photographed the tree covered in autumn leaves for her portfolio.",
        "The tree removal service cleared the fallen tree from the driveway.",
        "He identified the tree as a rare species found only in this region.",
        "The tree grew quickly in the rich soil of the garden plot.",
        "A tree was dedicated in the park in memory of the founder.",
        "She hung a birdhouse from a branch of the tree in the yard.",
        "The tree canopy provided natural cooling for the buildings nearby.",
        "He watered the newly planted tree every day until it was established.",
        "The tree was estimated to be over two hundred years old now.",
        "She studied tree growth patterns as part of her biology research.",
        "The tree had survived multiple storms and remained standing strong.",
        "A tree planting initiative aimed to increase green cover in the city.",
        "He leaned against the tree and enjoyed the shade on the warm day.",
        "The tree shed its leaves creating a carpet of gold on the ground.",
        "She collected samples from the tree for analysis in the lab.",
        "The ornamental tree added beauty to the landscaping of the property.",
        "He climbed the tree to rescue the cat that was stuck on a branch.",
        "The tree roots were causing damage to the sidewalk and needed attention.",
        "A tree lined boulevard is a characteristic feature of the neighborhood.",
        "She read about the ecological importance of tree in urban environments.",
        "The tree provided habitat for numerous bird species throughout the year.",
        "He chose a native tree species for the reforestation project effort.",
        "The tree was decorated with lights for the holiday festival celebration.",
        "She painted a watercolor of the tree at sunset from the overlook.",
        "The tree survived the drought thanks to its deep root system below.",
        "He measured the tree height and trunk diameter for the research survey.",
        "The tree was protected by local ordinance from being cut down.",
        "A new tree was planted for every one that was removed from the area.",
    ],
    "garden": [
        "She designed a rooftop garden for the apartment building residents.",
        "The garden center sold a wide variety of plants and gardening tools.",
        "He maintained the garden using organic methods and avoided all pesticides.",
        "The community garden became a gathering place for neighbors to socialize.",
        "She took a garden design course at the local community college.",
        "The garden was featured in a landscaping magazine for its unique design.",
        "He installed an irrigation system in the garden for efficient watering.",
        "The garden produced an impressive yield of vegetables this growing season.",
        "She volunteered at the garden teaching children about growing their own food.",
        "The botanical garden hosted an exhibition of rare tropical plant species.",
        "He built raised beds in the garden to improve drainage and soil quality.",
        "The garden was open to the public during the annual flower show event.",
        "She hired a professional landscaper to redesign the garden completely.",
        "The garden path was illuminated with solar powered lights at night.",
        "He composted kitchen waste and used it as fertilizer in the garden.",
        "The garden attracted pollinators like bees and butterflies throughout the season.",
        "She planted herbs in the garden for use in her kitchen recipes.",
        "The garden won first prize at the neighborhood beautification competition.",
        "He relaxed in the garden after a long day of work at the office.",
        "The garden fence was replaced with a more decorative wrought iron design.",
        "She grew exotic plants in the garden imported from tropical regions abroad.",
        "The garden water feature created a peaceful atmosphere for relaxation.",
        "He expanded the garden to include a section for growing berries.",
        "The garden soil was tested and amended with nutrients before planting.",
        "She enjoyed sitting in the garden listening to the birds sing each morning.",
        "The garden tools were organized neatly in the new storage shed.",
        "He attended a garden workshop on sustainable gardening techniques and methods.",
        "The garden provided fresh food for the family throughout the entire summer.",
        "She photographed the garden in every season to document the changes.",
        "The garden was a source of pride and joy for the whole community.",
    ],
    "river": [
        "The river cleanup project removed tons of waste from the waterway.",
        "She kayaked down the river enjoying the scenic views along the route.",
        "The river was monitored for pollution levels by the environmental agency.",
        "He photographed the river at dawn when the light was most beautiful.",
        "The river trail is popular with joggers and cyclists on weekends.",
        "The city invested in river restoration to improve the urban ecosystem.",
        "She took a river cruise through the historic district of the city.",
        "The river bank was reinforced to prevent erosion during heavy rainfall.",
        "He caught several fish in the river during the weekend fishing trip.",
        "The river provided a natural boundary between the two counties in the area.",
        "She organized a river rafting excursion for the outdoor adventure club.",
        "The river was designated as a protected waterway under new legislation.",
        "He built a cabin overlooking the river in a secluded forest area.",
        "The river festival attracted visitors from surrounding towns for the celebrations.",
        "She studied the river ecosystem as part of her environmental science thesis.",
        "The river level rose dramatically after three days of continuous heavy rain.",
        "He paddled his canoe along the river through the peaceful countryside.",
        "The river walk was enhanced with benches and new landscaping features.",
        "She collected water samples from the river for quality testing analysis.",
        "The river bridge was repaired after sustaining damage from the flood.",
        "He jogged along the river path every morning before work started.",
        "The river supported a diverse population of fish and aquatic plants.",
        "She attended a lecture about river conservation efforts in the region.",
        "The river was used for both recreation and water supply purposes.",
        "He learned about the history of the river from a local guide.",
        "The river delta was home to many endangered bird species in the area.",
        "She volunteered for the river monitoring program to track water quality.",
        "The river provided hydroelectric power to the communities downstream from the dam.",
        "He enjoyed the serenity of the river on quiet autumn afternoons.",
        "The river has been an important part of the regions history for centuries.",
    ],
}

# Gold standard: higher = more shift, lower = less shift
gold_standard = {
    "cell": 0.85,
    "mouse": 0.90,
    "apple": 0.88,
    "cloud": 0.82,
    "virus": 0.80,
    "net": 0.75,
    "water": 0.10,
    "house": 0.12,
    "book": 0.15,
    "tree": 0.08,
    "garden": 0.11,
    "river": 0.09,
}


def generate_corpus_file(sentences_dict, output_path):
    """Write sentences as JSON lines."""
    with open(output_path, 'w', encoding='utf8') as f:
        for word, sents in sentences_dict.items():
            for sent in sents:
                line = json.dumps({"content": sent}, ensure_ascii=False)
                f.write(line + '\n')
    print(f"Written {output_path}")


def generate_target_file(gold_standard, output_path):
    """Write target CSV with 'word' and 'mean' columns."""
    import csv
    with open(output_path, 'w', encoding='utf8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['word', 'mean'])
        for word, score in sorted(gold_standard.items()):
            writer.writerow([word, score])
    print(f"Written {output_path}")


if __name__ == '__main__':
    output_dir = os.path.join(os.path.dirname(__file__), 'data', 'demo')
    os.makedirs(output_dir, exist_ok=True)

    p1_path = os.path.join(output_dir, 'period1.txt')
    p2_path = os.path.join(output_dir, 'period2.txt')
    target_path = os.path.join(output_dir, 'target_words.csv')

    generate_corpus_file(period1_sentences, p1_path)
    generate_corpus_file(period2_sentences, p2_path)
    generate_target_file(gold_standard, target_path)

    print("\nDemo data generated successfully!")
    print(f"  Period 1 corpus: {p1_path}")
    print(f"  Period 2 corpus: {p2_path}")
    print(f"  Target words:    {target_path}")
    print(f"\nTarget words: {list(gold_standard.keys())}")
    print(f"Total words: {len(gold_standard)}")
    for word, score in sorted(gold_standard.items(), key=lambda x: -x[1]):
        print(f"  {word}: {score:.2f}")
